[package]
name = "abgc_derive"
version = "0.1.0"
authors = ["Laurence Tratt <laurie@tratt.net>"]
edition = "2018"
license = "Apache-2.0/MIT"

[lib]
proc-macro = true

[dependencies]
syn = "0.15"
quote = "0.6"

[dev-dependencies]
abgc = { path="../abgc" }
